package com.mentalhealth.platform.admin.entity;

public enum AuditAction {
    USER_BANNED,
    USER_UNBANNED,
    ROLE_CHANGED,
    FORUM_POST_REVIEWED,
    FORUM_POST_DISMISSED,
    FORUM_POST_ESCALATED_TO_SPECIALIST,
    REPORT_REVIEWED,
    REPORT_DISMISSED,
    REPORT_ESCALATED_TO_SPECIALIST,
    REPORT_IDENTITY_REVEALED,
    REPORT_SPECIALIST_RESPONDED,
    FORUM_POST_SPECIALIST_NOTE_ADDED
}
